name: CI
on:
  push:
    branches:
      - main
    tags:
      - *
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Magic Version
        uses: sinkcup/magic-version@v1.1.0

      - name: Pack
        run: |
          mkdir -p dist
          cp LICENSE README.md dist/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: demo-${{ env.MAGIC_VERSION }}
          path: dist
